### ISSUE TITLE
Q: How to store token

### ISSUE THREAD

**Issue by Kozlov-V** [ObjColumnist/MCSMKeychainItem#3]
I want use token-based authentication,
please, help me, how i can store auth token?
So, i want store:
- service
- account
- password
- token

Tell me way to store this
Thank you!

**Comment by ObjColumnist** [comment]
I would just create 2 Keychain items,

Service, Account and Password
Service, Account and Token (as a Password)

Most of the time when you use a token based system you don't need to store the password.

**Comment by Kozlov-V** [comment]
It is a good!
