### ISSUE TITLE
The 1.1 pod spec has not been published to Cocoapods

### ISSUE THREAD

**Issue by BennettSmith** [ObjColumnist/MCSMKeychainItem#5]
We are currently using the older 1.0.2 version of MCSMKeychainItem. Xcode 6 is complaining about some ARC related issues.  It appears that you have resolved these issued with the recent 1.1 changes.  Could you please publish the 1.1 pod spec and add a 1.1 tag so we can take advantage of these changes?

**Comment by ObjColumnist** [comment]
Sure, il try and get round to this over the weekend.

**Comment by ObjColumnist** [comment]
Should be fine now (the process has changed since I last submitted a pod spec), so let me know if you have any issues.
