### ISSUE TITLE
Same Unique Id for 2 different iPads

### ISSUE THREAD

**Issue by imrangnit** [ObjColumnist/MCSMKeychainItem#6]
Hi,
i have an issue where [MCSMApplicationUUIDKeychainItem applicationUUID] give me same Unique Id for 2 different iPads. Can anybody tell me in which condition i can get same Unique Id for different iPads? It is urgent if anybody also get this issue, please share your thoughts with me.

Thanks

**Comment by ObjColumnist** [comment]
Statistically it is nearly impossible for the same UUID to be generated.

Are they synced to the same iCloud Account by any chance? My only logical explanation is that it is be synced between them using iCloud.
